apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-rest
  labels:
    service: service-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      service-pod: service-rest-pod
  template:
    metadata:
      labels:
        service-pod: service-rest-pod
    spec:
      containers:
        - name: service-rest
          image: eu.gcr.io/abiding-orb-258221/diego-puzza@sha256:6192569ea67be97d4e77b59757b26119caf133c51f372cbd2ddf2010033b39d1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: rest-conf
              mountPath: /usr/src/app/conf
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "50m"
      volumes:
        - name: rest-conf
          configMap:
            name: service-rest-conf