apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb-standalone
    spec:
      containers:
        - name: mongodb-standalone
          image: mongo:4.0.8
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo/admin/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo/admin/MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: db-credentials-secret
              mountPath: /etc/mongo
              readOnly: true
            - name: mongodb-data
              mountPath: /data/db
          ports:
            - containerPort: 27017
      volumes:
        - name: db-credentials-secret
          secret:
            secretName: db-credentials
            items:
              - key: MONGO_ROOT_USERNAME
                path: admin/MONGO_ROOT_USERNAME
                mode: 0444
              - key: MONGO_ROOT_PASSWORD
                path: admin/MONGO_ROOT_PASSWORD
                mode: 0444
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: db-claim